name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [main]
    paths: ["**/*.vue", "**/*.ts", "**/*.scss", "nuxt.config.*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate       # ← Nuxt 静的ビルド
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main           # ← main ブランチをそのまま上書き
          folder: .output/public
          clean: true
